spring:
  datasource:
    username: twhiter
    password: TWhiter
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.118.38.24:3306/mobile_pay
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    password: TWhiter

server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeEnumsPackage: com.springtest.demo.enums




