spring:
  datasource:
    username: twhiter
    password: TWhiter
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:1234/mobile_pay

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: 34.118.35.246
    password: TWhiter

server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeEnumsPackage: com.springtest.demo.enums


